"""Generate thin, safe agent adapters from .engineering/config.yaml."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable
import json

from .config import HarnessConfig


MARKER_START = "<!-- aplomo:start -->"
MARKER_END = "<!-- aplomo:end -->"
LEGACY_MARKER_START = "<!-- engineering-harness:start -->"
LEGACY_MARKER_END = "<!-- engineering-harness:end -->"


def _hook_command(source: str) -> str:
    return f"aplomo hook --source {source}"


def _mcp_server() -> Dict[str, object]:
    return {"type": "stdio", "command": "aplomo", "args": ["mcp", "--root", "."]}


def generated_files(config: HarnessConfig) -> Dict[str, str]:
    files: Dict[str, str] = {}
    if config.integrations.get("hooks", True):
        if "cursor" in config.agents:
            files[".cursor/hooks.json"] = _json({
                "version": 1,
                "hooks": {
                    "sessionStart": [{"command": _hook_command("cursor")}],
                    "afterFileEdit": [{"command": _hook_command("cursor")}],
                    "afterShellExecution": [{"command": _hook_command("cursor")}],
                },
            })
        if "claude" in config.agents:
            files[".claude/settings.json"] = _json({
                "hooks": {
                    "SessionStart": [{"hooks": [{"type": "command", "command": _hook_command("claude")}]}],
                    "PostToolUse": [{"matcher": "Write|Edit", "hooks": [{"type": "command", "command": _hook_command("claude")}]}],
                    "Stop": [{"hooks": [{"type": "command", "command": _hook_command("claude")}]}],
                }
            })
        if "codex" in config.agents:
            files[".codex/hooks.json"] = _json({
                "description": "Generated by Aplomo from .engineering/config.yaml",
                "hooks": {
                    "SessionStart": [{"hooks": [{"type": "command", "command": _hook_command("codex")}]}],
                    "PostToolUse": [{"matcher": "Write|Edit", "hooks": [{"type": "command", "command": _hook_command("codex")}]}],
                    "Stop": [{"hooks": [{"type": "command", "command": _hook_command("codex")}]}],
                },
            })

    if config.integrations.get("mcp", True):
        if "cursor" in config.agents:
            files[".cursor/mcp.json"] = _json({"mcpServers": {"aplomo": _mcp_server()}})
        if "claude" in config.agents:
            files[".mcp.json"] = _json({"mcpServers": {"aplomo": _mcp_server()}})
        if "codex" in config.agents:
            files[".codex/config.toml"] = (
                "# Generated by Aplomo. Edit .engineering/config.yaml instead.\n"
                "[mcp_servers.aplomo]\n"
                'command = "aplomo"\n'
                'args = ["mcp", "--root", "."]\n'
            )

    if config.integrations.get("skills", True):
        if "cursor" in config.agents:
            files[".cursor/rules/aplomo.mdc"] = CURSOR_RULE
        if "codex" in config.agents:
            files[".agents/skills/aplomo-review/SKILL.md"] = SKILL
        if "claude" in config.agents:
            files[".claude/skills/aplomo-review/SKILL.md"] = SKILL
    return files


def install_integrations(root: Path, config: HarnessConfig) -> Dict[str, str]:
    statuses: Dict[str, str] = {}
    previous_manifest = _read_manifest(root)
    for relative, content in generated_files(config).items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and relative not in previous_manifest and path.read_text(encoding="utf-8") != content:
            statuses[relative] = "skipped (existing, not owned by Aplomo)"
            continue
        path.write_text(content, encoding="utf-8")
        statuses[relative] = "installed"
    if "codex" in config.agents:
        statuses["AGENTS.md"] = _merge_instruction_file(root / "AGENTS.md", AGENTS_BLOCK)
    if "claude" in config.agents:
        statuses["CLAUDE.md"] = _merge_instruction_file(root / "CLAUDE.md", CLAUDE_BLOCK)
    manifest_path = root / ".engineering" / "generated-manifest.json"
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    owned = sorted(relative for relative, status in statuses.items() if status in {"installed", "updated"})
    manifest_path.write_text(_json({"version": 1, "generator": "aplomo", "files": owned}), encoding="utf-8")
    return statuses


def _read_manifest(root: Path) -> Iterable[str]:
    path = root / ".engineering" / "generated-manifest.json"
    if not path.exists():
        return set()
    try:
        return set(json.loads(path.read_text(encoding="utf-8")).get("files", []))
    except (json.JSONDecodeError, OSError):
        return set()


def _merge_instruction_file(path: Path, body: str) -> str:
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    legacy = LEGACY_MARKER_START in existing and LEGACY_MARKER_END in existing
    start = LEGACY_MARKER_START if legacy else MARKER_START
    end = LEGACY_MARKER_END if legacy else MARKER_END
    block = f"{MARKER_START}\n{body.strip()}\n{MARKER_END}"
    if start in existing and end in existing:
        before = existing.split(start, 1)[0].rstrip()
        after = existing.split(end, 1)[1].lstrip()
        content = "\n\n".join(part for part in (before, block, after) if part)
    else:
        content = "\n\n".join(part for part in (existing.rstrip(), block) if part)
    path.write_text(content + "\n", encoding="utf-8")
    return "updated"


def _json(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


AGENTS_BLOCK = """
## Aplomo

The engineering source of truth is `.engineering/`. Before adding an abstraction:

1. Search the repository for an existing equivalent.
2. Understand the relevant module boundaries.
3. Explain why extending the existing pattern is insufficient.
4. Review the plan and final diff with the `aplomo` MCP tools when available.

Do not edit generated agent integrations directly. Update `.engineering/config.yaml` and run `aplomo install`.
"""

CLAUDE_BLOCK = """
## Aplomo

Treat `.engineering/` as the repository's engineering source of truth. Before adding an abstraction, use the Aplomo MCP tools to understand the repository, search for an existing pattern, review the plan, and review the final diff. Edit `.engineering/config.yaml` and run `aplomo install` instead of editing generated integrations.
"""

SKILL = """---
name: aplomo-review
description: Review plans, architecture choices, and diffs against repository conventions.
---

# Aplomo review

Use this workflow before introducing a new abstraction or completing a non-trivial change:

1. Call `aplomo_understand_repo`.
2. Call `aplomo_find_existing_patterns` for the concept being introduced.
3. Call `aplomo_review_plan` before implementation.
4. Call `aplomo_review_diff` before declaring completion.

The repository's `.engineering/` directory is authoritative. Agent-specific files are generated adapters.
"""

CURSOR_RULE = """---
description: Apply the repository's Aplomo engineering workflow
alwaysApply: true
---

Treat `.engineering/` as the source of truth. Before adding an abstraction, use the Aplomo MCP tools to understand the repository, search existing patterns, review the plan, and review the final diff. Update `.engineering/config.yaml` and run `aplomo install` instead of editing generated integrations.
"""
